# Generated by Django 3.2 on 2021-04-26 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('work_status', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.CharField(max_length=20, unique=True)),
                ('e_name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='LogDateFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('log_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLogAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=264)),
                ('created_by_date', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=264)),
                ('changed_by_date', models.DateTimeField(auto_now=True)),
                ('comments', models.CharField(blank=True, max_length=264)),
                ('daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.dailylog')),
            ],
        ),
        migrations.AddField(
            model_name='dailylog',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee'),
        ),
    ]
