# Generated by Django 3.2 on 2021-04-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailylog',
            name='emp_date_ckey',
            field=models.CharField(default=None, max_length=254, unique=True),
        ),
    ]
