# Generated by Django 3.2 on 2021-04-26 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_dailylog_emp_date_ckey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailylog',
            name='emp_date_ckey',
            field=models.CharField(default=models.AutoField(primary_key=True, serialize=False), max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='dailylog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
