# Generated by Django 3.2 on 2021-04-27 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDailyLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sheet_count', models.IntegerField(default=0)),
                ('sheet_residue_count', models.IntegerField(default=0)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductLogDateFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('log_status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProductDailyLogAdditional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=264)),
                ('created_by_date', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.CharField(max_length=264)),
                ('changed_by_date', models.DateTimeField(auto_now=True)),
                ('comments', models.CharField(blank=True, max_length=264)),
                ('product_daily_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productdailylog')),
            ],
        ),
    ]
