# Generated by Django 3.2 on 2021-04-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdailylog',
            name='date',
            field=models.DateField(default='2021-04-27', unique=True),
        ),
    ]
